### ISSUE TITLE
PoolBasedBinaryClassification yaml file not accurate

### ISSUE THREAD

**Issue by dconathan** [nextml/NEXT#110]
The [yaml](https://github.com/nextml/NEXT/blob/redux/next/apps/Apps/PoolBasedBinaryClassification/PoolBasedBinaryClassification.yaml) file should include that the targets need a 'meta' dictionary pointing to a 'features' vector... because the app/algorithm requires a feature vector associated with each target.  I believe it should be something like:

```
        targets:
          description: targets
          type: oneof
          values:
            targetset:
              description: A target set.
              type: targetset
              values: []
            meta:
              type: dict
              values:
                  features:
```
etc...
